char *killLogSingle[] = {
	"%s was bombed%s",
	"%s lit her own fart%s",
	"%s stepped on her own grenade%s",
	"%s lit his own fart%s",
	"%s stepped on his own grenade%s",
	"%s 'sploded%s",
	"%s sacrificed himself%s",
	"%s was SLAPPED to Death by the Server Admin%s",
	"%s was struck down by the Server Admin%s",
	"%s was nuked by the Server Admin%s",
	"%s was killed by a flag%s",
	"%s wtf..%s",
	"%s did the lemming thing%s",
	"%s killed herself%s",
	"%s killed himself%s",
	"%s killed itself%s",
	"%s decided it was all too much%s",
	"%s was crushed to death%s",
	"%s decided to swim with the fishes, permanently%s",
	"%s melted%s",
	"%s does a back flip into the lava%s",
	"%s saw the light%s",
	"%s was killed by some well placed HURT%s",
	NULL
};

char *killLog1[] = {
	"%s was curb-stomped by %s",
	"%s tried to invade%s's personal space.",
	"%s was sliced a new orifice by %s",
	"%s managed to sheath %s's flying knife in their flesh.",
	"%s was pistol whipped by %s",
	"%s got plastic surgery with %s's Glock.",
	"%s got a whole lot of hole from %s's DE round.",
	"%s was given a new breathing hole by %s's Colt 1911.",
	"%s was turned into peppered steak by %s's SPAS blast.",
	"%s danced the UMP tango to %s's sweet sweet music.",
	"%s was MP5K spammed without mercy by %s.",
	"%s was minced to death by %s's Mac 11.",
	"%s played 'catch the shiny bullet' with %s's LR-300 rounds.",
	"%s was on the wrong end of %s's G36.",
	"%s was torn asunder by %s's crass AK103.",
	"%s got a lead enema from %s's retro M4.",
	"%s was taken out by %s's PSG1. Plink!",
	"%s HEARD %s's HK69 gren... didn't AVOID it. Sucka.",
	"%s suffered %s's HK69 Grenade Enema.",
	"%s got himself some lovin' from %s's boot o' passion.",
	"%s was flashed by %s and dropped dead.",
	"%s was smoked by %s and dropped dead.",
	"%s has become a nasty stain thanks to %s's HE gren.",
	"%s was BBQ'ed by %s's exploding monkey.",
	"%s managed to slow down %s's SR-8 round just a little.",
	"%s managed to slow down %s's SR-8 round just a little. NEEP NEEP!",
	"%s bled to death from %s's attacks.",
	"%s got shredded to pieces by %s's Negev.",
	"%s got nailed to the wall by %s's Negev.",
	"%s was shot down by %s's guided HK69 'nade.",
	"%s thought it was %s's pet flying squirrel and tried to catch it. BAD SQUIRREL, BAD.",
	"%s was nuked by accident, intented target was %s",
	"%s was retired from the field of combat by %s",
	"%s got %s's foot broken off in their ass.",
	NULL
};

char *killLog2[] = {
	"%s [Curb-stomp] %s.",
	"%s [Knife] %s.",
	"%s [Knife thrown] %s.",
	"%s [Beretta] %s.",
	"%s [Glock] %s.",
	"%s [Desert Eagle] %s.",
	"%s [Colt 1911] %s.",
	"%s [SPAS] %s.",
	"%s [UMP45] %s.",
	"%s [MP5K] %s.",
	"%s [Mac 11] %s.",
	"%s [LR300] %s.",
	"%s [G36] %s.",
	"%s [AK103] %s.",
	"%s [M4] %s.",
	"%s [PSG1] %s.",
	"%s [HK69] %s.",
	"%s [Boot] %s.",
	"%s [Smoke] %s.",
	"%s [HE] %s.",
	"%s [SR8] %s.",
	"%s [Bleed] %s.",
	"%s [Negev] %s.",
	"%s [HK69] %s.",
	NULL
};

char *killLog3[] = {
	"%s has been killed by %s.",
	NULL
};
